### ISSUE TITLE
Encode Arguments out of order

### ISSUE THREAD

**Issue by richardssam** [AcademySoftwareFoundation/EncodingGuidelines#40]
The encoding arguments that end up in the OTIO file, are ordered differently to what is in the YML file, which means you cannot look at the list of encoding arguments, and assume that is the right order.

It looks like something bad is happening in the run_wedges code in ffmpeg_encoder.py, but its not obvious what it is.

**Comment by apetrynet** [comment]
Hmm. Could this be related to the merging of the arguments? I'll have to investigate how pyyaml deals with updating the mapping aka dict.
