### ISSUE TITLE
Problem replicating the matching chip-color-test.py's libswscale test (ie. the one where the output matches the original)

### ISSUE THREAD

**Issue by ggarra13** [AcademySoftwareFoundation/EncodingGuidelines#83]
I have cloned the repository and run chip-color-test.py.  I do not have an FFmpeg with VFR, as I only cared about matching the results visually.  I am using FFmpeg 6.0.  I am comparing the images with my viewer (mrv2 and with iv) and they look the same:

`
mrv2 chip-chart-yuvconvert/chip-chart-1080-noicc-spline444out_color_matrix.png ../sourceimages/chip-chart-1080-noicc.png
`

However, if I compare the actual movie file to the original -noicc.png, I don't get a match:

`
mrv2 chip-chart-yuvconvert/spline444out_color_matrixfull.mp4 ../sourceimages/chip-chart-1080-noicc.png
`

or:

`
iv chip-chart-yuvconvert/spline444out_color_matrixfull.mp4 ../sourceimages/chip-chart-1080-noicc.png
`

I am trying to understand why.
```[tasklist]
### Tasks
```

**Comment by richardssam** [comment]
Sorry I missed this issue, I'll take a look.

**Comment by richardssam** [comment]
I know this ticket is rather old, did any of the changes we saw a month ago make a difference here?

**Comment by ggarra13** [comment]
Quite frankly, I forgot about this issue.  It is probably not relevant now.  I will be closing it.

**Comment by ggarra13** [comment]
Yep.  I just checked with mrv2 and it matches perfectly now.  Thanks for your help!
